num_blocks: 5
block_height: 0.035
dissassemble: true # Whether tower should be dissassembled after
preallocation: true # Whether positions of blocks are provided
tower: {
  position: {x: 0.1, y: -0.03, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
block_0: {
  position: {x: 0.1, y: -0.15, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
block_1: {
  position: {x: 0.2, y: -0.20, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
block_2: {
  position: {x: 0.1, y: -0.25, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
block_3: {
  position: {x: 0.2, y: -0.30, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
block_4: {
  position: {x: 0.1, y: -0.35, z: 0.019},
  # orientation: {x: 0.707, y: 0, z: 0, w: 0.707}
  orientation: {x: 0, y: 0, z: 0, w: 1}
}
